### ISSUE TITLE
[DEV] Extract Material Design to shared module instead of product module

### ISSUE THREAD

**Issue by YangLin404** [YangLin404/resto-app#6]

**Comment by YangLin404** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[DEV] Extract Material Design to shared module instead of product module](https://trello.com/c/FPB3NWDj/9-dev-extract-material-design-to-shared-module-instead-of-product-module)

**Comment by denzelvb** [comment]
Closed as we do not use material design in my products anymore
